import { colours } from '../../styles/colours';

export const gamePageStyles = {
    backButton: {
        color: colours.textMuted,
        textTransform: 'none',
        mb: 2,
        px: 0,
        '&:hover': { color: colours.text, backgroundColor: 'transparent' },
    },
    header: { mb: 4 },
    gameTitle: { color: colours.text, fontWeight: 700, mb: 1 },
    ratingRow: { display: 'flex', alignItems: 'center', gap: 1.5, mb: 2 },
    ratingText: { color: colours.textMuted, fontSize: '0.9rem' },
    categoriesRow: { display: 'flex', flexWrap: 'wrap', gap: 1, mb: 2 },
    categoryChip: {
        backgroundColor: colours.cardBorder,
        color: colours.textCategory,
        border: `1px solid ${colours.cardBorderAccent}`,
        fontSize: '0.75rem',
    },
    bio: { color: colours.textDim, lineHeight: 1.7, maxWidth: 720 },
    reviewsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: 1.5,
        mb: 4,
        maxWidth: 560,
        mx: 'auto',
    },
    reviewCard: {
        backgroundColor: colours.card,
        border: `1px solid ${colours.cardBorder}`,
        borderRadius: 2,
        p: 1.5,
    },
    reviewHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        mb: 0.5,
    },
    reviewUsername: { color: colours.text, fontWeight: 600, fontSize: '0.85rem' },
    reviewText: { color: colours.textDim, fontSize: '0.85rem' },
    seeMoreButton: {
        alignSelf: 'center',
        textTransform: 'none',
        borderColor: colours.inputBorder,
        color: colours.textMuted,
        '&:hover': { borderColor: colours.text, color: colours.text },
    },
    starRatingWrapper: { mb: 2 },
    submitButton: { textTransform: 'none', fontWeight: 600, px: 4, py: 1.2, borderRadius: 2 },
    signInPrompt: { color: colours.textMuted, fontSize: '0.85rem', mt: 1.5 },
    divider: { borderColor: colours.cardBorder, mb: 4 },
    sectionHeading: { color: colours.text, fontWeight: 700, mb: 2 },
    noReviews: { color: colours.textMuted, mb: 4 },
    loadingSpinner: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: '50vh',
    },
    starRatingOpaque: { mb: 2, opacity: 1, pointerEvents: 'auto' },
    starRatingDimmed: { mb: 2, opacity: 0.4, pointerEvents: 'none' },
};
